### PR TITLE
Feature: Add PublicList class

### PR DESCRIPTION
**Pull request by glensc**
Add PublicList for:
- https://github.com/Taxel/PlexTraktSync/issues/1826

```py
movie_list = PublicList.load(trakt_id)
print(movie_list.description)

for m in movie_list:
  print(f"{m.rank}. {m.title}: {m.listed_at} {m.trakt}")
```

Actual usage example:
- https://github.com/Taxel/PlexTraktSync/pull/1843

Tests in a separate PR:
- https://github.com/glensc/python-pytrakt/pull/44

### CODE REVIEW

**Comment by glensc** [comment]
The module name where it's placed is perhaps odd:

```py
from trakt.users import PublicList
```

**Comment by glensc** [comment]
@simonc56 any comments?

**Comment by simonc56** [comment]
I didn't test.
Maybe some [tests](https://github.com/glensc/python-pytrakt/blob/main/tests/test_users.py) for PublicList could be helpful.

**Comment by glensc** [comment]
Tests in a separate PR:
- https://github.com/glensc/python-pytrakt/pull/44

**Pull request merged**
